### ISSUE TITLE
整理僵尸Demo工程

### ISSUE THREAD

**Issue by XianWorld** [pangaeastudio/pangaeastudio.github.io#12]
- 支持OC+Hydra小空间交互。
- 简单整理输入控制接口以便摄像头定位设备接入。

**Comment by skistua** [comment]
- Bruce Fight (僵尸Demo) 整理初步完成
  - 去除了 OpenVR 的 Script 和 Dll. 目前OC 的 Dll 和 OpenVR的 动态库有冲突,同时存在运行会崩溃.
  -  更换了 Oculus DK2 和 LeapMotion 的 Dll.
- 实现了LeapMotion 和 Razer Hydra 类JoyStick 的 输入设备简单封装.
- 创建了可运行的 测试Demo.  
  - For Leapmotion `pangaeastudio/vrgame-bruceli/Assets/ViveTest/Scenes/Hit Reaction 4.unity`
  - For Hydra `pangaeastudio/vrgame-bruceli/Assets/ViveTest/Scenes/HydraTest.unity`
