### ISSUE TITLE
VR小说连载——第一期

### ISSUE THREAD

**Issue by XianWorld** [pangaeastudio/pangaeastudio.github.io#17]
- 9月24日~25日完成提交给相关VR媒体评估。
- 9月30日前发表，10月1日假期后评估反馈。

**Comment by kque** [comment]
黑暗浓的像一道裹尸布，把所有秘密和罪恶都包裹的一丝不露。

黑暗中嗤的一声，一缕微光撕开幕布，露出黑暗中的隐藏之物。

这是一处停尸房，因为有一张被白布包裹的床，从白布起伏的形状推测——下面应该躺着一具尸体。

墙上的白炽灯布满油污，忽明忽暗，在这阴冷的犹如墓穴的房间里，似乎每一缕阴影里都藏有一个鬼魂，不断地发出嗤嗤的嘲笑。似乎是响应这空间里诡异的嘲笑，凄白的裹尸布突然抖动了一下。

——这具被裹尸布包裹的尸体，坐了起来。

作为一具合格的尸体，曝露出来的这具男尸面孔上，并没有表现出从另一个世界归来的骇人景象。只是有些如同梦寐初醒的呆滞，甚至连肤色都算不上惨白，似乎还带着几分新死未久的余温。

在瞬间的呆滞之后，男尸的眼瞳里突然如同注入了某种神秘力量，一缕逐渐生动的光芒，从灰白的世界里挣脱了出来。映入眼中的昏暗光景，让这具似乎刚从死亡世界里游历归来的男尸，突然从床上窜了起来，动作敏捷的像一头猎豹。

很快，他就为刚才那敏捷的动作付出了代价——一阵撕心裂肺的巨痛，无端地出现在脑海之中，像海面上铺天盖地的暴风一般，将他所有的意识彻底淹没。这疼痛是如此地剧烈，不但将他呻吟的力量带走了，甚至几乎将他呼吸的力气也一并夺去。

阴影中嗤嗤的嘲笑声，骤然变得急密，昏暗的灯光在他脸上闪烁不定，原本呆滞的表情因剧痛而扭曲，却显出了几分活人的生动。

不知过了多久，疼痛终于渐渐退去了，在四周刺鼻的腥臭中，男子重新从地上坐了起来。稍微思考，脑袋就痛得似乎要炸开，只好背靠着墙壁端详四周。

没有任何东西能证明自己此刻身处的不是地狱，在这片幽暗的空间里，除了身旁的这张床，再无他物。

地上的血迹蔓延，向那灯光照不透的黑暗——那被昏暗所吞没的一切，是深不可测的黑暗世界。

**Comment by XianWorld** [comment]
挺有感觉的
